apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources: 
  - ../../base/homepage/
images: 
  - name: ghcr.io/gethomepage/homepage
    newTag: v1.10.1

patches:
  - target: 
      kind: ConfigMap
      name: homepage
      namespace: homepage
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: homepage
        namespace: homepage
      data:
        services.yaml: |
          - HomeLab:
              - Grafana:
                  href: https://grafana-staging.crpruett.net
                  description: Grafana
                  icon: grafana
              - Mealie:
                  href: https://mealie-staging.crpruett.net
                  description: I love food
                  icon: mealie
              - Synology:
                  href: https://crpruett.us1.quickconnect.to/#/signin
                  description: Synology NAS DS225+
                  icon: si-synology
              - Kubernetes Metrics:
                  href: https://live.crpruett.net/ui
                  description: Python-based Kubernetes Metrics App
                  icon: si-pyg
            
          - Consuming:
              - Destructoid:
                  href: https://www.destructoid.com/
                  description: Gaming/Cyber News
                  icon: si-robotframework
              - Youtube:
                  href: https://www.youtube.com
                  icon: youtube
          - Publishing:
              - LinkedIn:
                  href: https://linkedin.com/in/crpruett
                  description: LinkedIn
                  icon: linkedin
              - Twitter/X:
                  href: https://x.com/LogosArete
                  description: TwitX
                  icon: twitter
              - Substack:
                  href: https://substack.com/@crpruett
                  description: Substack
                  icon: si-substack
              - Youtube Creator:
                  href: https://www.youtube.com/@democracyofthedead9282
                  description: Classic Youtube Account
                  icon: si-youtubestudio
          - Misc:
              - WutPutHere:
                  href: http://localhost/
                  description: Homepage is ðŸ˜Ž
