apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources: 
  - ../../base/homepage/
  - configmap.yaml
images: 
  - name: ghcr.io/gethomepage/homepage
    newTag: v1.10.0
