apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - clusterrole.yaml
  - configmap.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - ingress.yaml
