apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pagerduty-test
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: pd.test
      rules:
        - alert: PagerDutyPipelineTest
          expr: vector(1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "PagerDuty pipeline test alert"
