apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/crpruett
  services.yaml: |
    - HomeLab:
        - Grafana:
            href: https://grafana.crpruett.net
            description: Grafana
            icon: grafana
        - Mealie:
            href: https://mealie.crpruett.net
            description: I love food
            icon: mealie
        - Synology:
            href: https://crpruett.us1.quickconnect.to/#/signin
            description: Synology NAS DS225+
            icon: si-synology
            
    - Consuming:
        - Destructoid:
            href: https://www.destructoid.com/
            description: Gaming/Cyber News
            icon: si-robotframework
        - Youtube:
            href: https://www.youtube.com
            icon: youtube
    - Publishing:
        - LinkedIn:
            href: https://linkedin.com/in/crpruett
            description: LinkedIn
            icon: linkedin
        - Twitter/X:
            href: https://x.com/LogosArete
            description: TwitX
            icon: twitter
        - Substack:
            href: https://substack.com/@crpruett
            description: Substack
            icon: si-substack
        - Youtube Creator:
            href: https://www.youtube.com/@democracyofthedead9282
            description: Classic Youtube Account
            icon: si-youtubestudio
    - Misc:
        - WutPutHere:
            href: http://localhost/
            description: Homepage is ðŸ˜Ž
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank

  docker.yaml: ""





















